var workLang = {

    cancel      : '<?php _e('Cancel','works'); ?>',
    check       : '<?php _e('Verifying data...','works'); ?>',
    notitle     : '<?php _e('You must provide a title for this page!','works'); ?>',
    nogroup     : '<?php _e('You must select at least one group if you want to save this work as private!','works'); ?>',
    notime      : '<?php _e('You must specify a date to program the publication of this project!','works'); ?>',
    nocategory  : '<?php _e('You must to select at least one category for this project!','works'); ?>',
    ok          : '<?php _e('Ok','works'); ?>',
    savedraft   : '<?php _e('Save as Draft', 'works'); ?>',
    savepublish : '<?php _e('Save and Publish', 'works'); ?>',
    saveprivate : '<?php _e('Save as Private', 'works'); ?>',
    saveschedule: '<?php _e('Schedule Publication', 'works'); ?>',
    done        : '<?php _e('Data saved successfully', 'works'); ?>',
    delete_works: '<?php _e('Do you really want to delete selected works?','works'); ?>',
    select_work : '<?php _e('You must select some work before to execute this action!','works'); ?>',
    addnew      : '<span class="fa fa-plus"></span> <?php _e('Add New', 'works'); ?>',
    noVideoUrl  : '<?php _e('You must provide a video URL in order to add a new video!', 'works'); ?>',
    noVideoTitle  : '<?php _e('You must provide a <strong>video title</strong> in order to add a new video!', 'works'); ?>',
    edit : '<?php _e('Edit', 'works'); ?>',
    delete : '<?php _e('Delete', 'works'); ?>',
    update : '<span class="fa fa-check"></span> <?php _e('Save Changes', 'works'); ?>',
    addVideo : '<span class="cu-icon"><span class="fa fa-plus"></span></span> <?php _e('Add Video', 'works'); ?>',
    confirmDelete : '<?php _e('Do you really want to delete selected video?', 'works'); ?>',

};
